# Generated by Django 3.0.5 on 2020-04-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('ISIN', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.BigIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mutual_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutual_fund_track.MutualFund')),
            ],
            options={
                'unique_together': {('mutual_fund', 'date')},
                'index_together': {('mutual_fund', 'date')},
            },
        ),
    ]
