# Generated by Django 3.0.5 on 2020-04-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_fund_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfundvalue',
            name='value',
            field=models.FloatField(),
        ),
    ]
